<a href="https://colab.research.google.com/github/ThunDroid1/Ujjwal_RL/blob/main/EXP5_QLearning_RL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

env_matrix = np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1, -1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100]
])

num_states, num_actions = env_matrix.shape
Q = np.zeros((num_states, num_actions))

gamma = 0.8

sequence = [1, 3]

for state in sequence:
    possible_actions = np.where(env_matrix[state] >= 0)[0]

    for action in possible_actions:
        Q[state, action] = env_matrix[state, action] + gamma * np.max(Q[action])

    print("Q-table after state", state)
    print(Q)

print("Final Q-table:")
print(Q)

Q-table after state 1
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
Q-table after state 3
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
Final Q-table:
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]


In [ ]:
import numpy as np

# Define the environment matrix
env_matrix = np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1, -1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100]
])

# Initialize the Q-table with zeros
num_states, num_actions = env_matrix.shape
Q = np.zeros((num_states, num_actions))

# Set hyperparameters
gamma = 0.8

# Specify the number of iterations
num_iterations = int(input("Enter the number of iterations: "))

for iteration in range(num_iterations):
    # Randomly choose a state
    state = np.random.randint(0, num_states)

    # Find the non-negative Q-values for the possible actions in the current state
    possible_actions = np.where(env_matrix[state] >= 0)[0]

    # Update the Q-values for each possible action
    for action in possible_actions:
        Q[state, action] = env_matrix[state, action] + gamma * np.max(Q[action])

    # Print the updated Q-table
    #print("Q-table after iteration", iteration + 1)
    print("Q-table after iteration", state)
    print(Q)

print("Final Q-table:")
print(Q)

Enter the number of iterations: 4
Q-table after iteration 3
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Q-table after iteration 5
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]]
Q-table after iteration 5
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 180.]]
Q-table after iteration 2
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 180.]]
Final Q-table:
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   