<a href="https://colab.research.google.com/github/ThunDroid1/Ujjwal_RL/blob/main/EXP8_RL_ValueIteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
P = np.array([
    [[0.1, 0.9], [0.8, 0.2]],
    [[0.6, 0.4], [0.1, 0.9]],
    [[0.2, 0.8], [0.6, 0.4]],
    [[0.8, 0.2], [0.9, 0.1]]
])

R = np.array([[10, -1], [-1, 10], [-1, 10], [-1, 10]])

gamma = 0.9

In [ ]:
def value_iteration(P, nS, nA, gamma=0.9):
    V = np.zeros(nS)
    epsilon = 1e-20

    while True:
        delta = 0
        for s in range(nS):
            v = V[s]
            V[s] = np.max(np.sum(P[s][a][s] * (r + gamma * V[s]) for a, r in enumerate(R[s])) for s in range(nS))
            delta = max(delta, abs(v - V[s]))
        if delta < epsilon:
            break

    policy = np.zeros((nS, nA), dtype=int)
    for s in range(nS):
        a = np.argmax(np.sum(P[s][a][s] * (r + gamma * V[s]) for a, r in enumerate(R[s])) for s in range(nS))
        policy[s] = a

    return policy, V

In [ ]:
nS = 4  # number of states
nA = 2  # number of actions

P = np.random.rand(nS, nA, nS)
R = np.random.rand(nS, nA)

policy, V = value_iteration(P, nS, nA)

print("Policy:")
print(policy)
print("State Value Function:")
print(V)


TypeError: ignored

In [ ]:
import numpy as np

def value_iteration(P, nS, nA, gamma=0.9, epsilon=1e-6):
    V = np.zeros(nS)
    policy = np.zeros(nS, dtype=int)

    while True:
        delta = 0
        for s in range(nS):
            v = V[s]
            Q_values = [np.sum(P[s][a][s] * (r + gamma * V[s]) for a, r in enumerate(R[s])) for s in range(nS)]
            V[s] = np.max(Q_values)
            policy[s] = np.argmax(Q_values)
            delta = max(delta, abs(v - V[s]))

        if delta < epsilon:
            break

    return policy, V

P = np.random.rand(nS, nA, nS)
R = np.random.rand(nS, nA)

nS = 4  # number of states
nA = 2  # number of actions

policy, V = value_iteration(P, nS, nA)

print("Policy:")
print(policy)
print("State Value Function:")
print(V)


Policy:
[1 1 1 1]
State Value Function:
[34.31207842 34.31207842 34.31207938 34.31207938]


<ipython-input-5-5c2815a1d7b0>:12: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  Q_values = [np.sum(P[s][a][s] * (r + gamma * V[s]) for a, r in enumerate(R[s])) for s in range(nS)]


In [ ]:
import numpy as np

def value_iteration(P, nS, nA, gamma=0.9, epsilon=1e-6):
    V = np.zeros(nS)
    policy = np.zeros(nS, dtype=int)

    while True:
        delta = 0
        for s in range(nS):
            v = V[s]
            # Fix the naming conflict by using a different variable for the inner loop
            Q_values = [np.sum(P[s][a][s_prime] * (r + gamma * V[s_prime]) for a, r in enumerate(R[s_prime])) for s_prime in range(nS)]
            V[s] = np.max(Q_values)
            policy[s] = np.argmax(Q_values)
            delta = max(delta, abs(v - V[s]))

        if delta < epsilon:
            break

    return policy, V

# Define the number of states and actions before using them
nS = 4  # number of states
nA = 2  # number of actions

# Example usage:
# Assuming you have P and R defined somewhere before calling the function
P = np.random.rand(nS, nA, nS)
R = np.random.rand(nS, nA)

policy, V = value_iteration(P, nS, nA)

print("Policy:")
print(policy)
print("State Value Function:")
print(V)


Policy:
[0 0 0 0]
State Value Function:
[inf inf inf inf]


<ipython-input-15-c423702ba4b6>:12: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  Q_values = [np.sum(P[s][a][s_prime] * (r + gamma * V[s_prime]) for a, r in enumerate(R[s_prime])) for s_prime in range(nS)]
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:2292: RuntimeWarning: overflow encountered in double_scalars
  res = _sum_(a)
<ipython-input-15-c423702ba4b6>:15: RuntimeWarning: invalid value encountered in double_scalars
  delta = max(delta, abs(v - V[s]))
